#!/bin/sh -e

case "$1" in
    remove)
    ;;

    purge)
    rm -f /etc/hostname
    rm -f /etc/NetworkManager/system-connections/usb0
    rm -f /etc/NetworkManager/system-connections/usb0.dpkg-save
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac
